# config/_default/languages.en.toml

title = "Sourabh Nair"

[author]
name = "Sourabh Nair"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "DevOps Engineer"
links = [
  { twitter = "https://twitter.com/username" }
]

