# config/_default/languages.en.toml

title = "Sourabh Nair"

[author]
name = "Sourabh Nair"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "DevOps Engineer"
links = [
  { email = "mailto:email@code22.in" },
  { link = "https://code22.in/" },
  { github = "https://github.com/devopsnsourabh" },
  { telegram = "https://t.me/username" },
]

